import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout/Layout'
import SectionExpertise from '../components/sections/section-expertise/SectionExpertise'
import SectionHero from '../components/sections/section-hero/SectionHero'
import SectionPortfolio from '../components/sections/section-portfolio/SectionPortfolio'
import SectionServices from '../components/sections/section-services/SectionServices'

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Datalite</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SectionHero />
      <SectionServices />
      <SectionExpertise />
      <SectionPortfolio />
    </Layout>
  )
}

export default Home
